### ISSUE TITLE
尽快修复这个crash问题

### ISSUE THREAD

**Issue by Leifzhang** [tencentyun/httpdns-android-sdk#4]
java.lang.ArrayIndexOutOfBoundsException: length=10; index=10
	at java.util.ArrayList.add(ArrayList.java:442)
	at com.tencent.beacon.event.UserAction.onUserAction(SourceFile:213)
	at com.tencent.beacon.event.UserAction.onUserAction(SourceFile:195)
	at com.tencent.msdk.dns.MSDKDnsResolver.a(Unknown Source)
	at com.tencent.msdk.dns.e.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.os.HandlerThread.run(HandlerThread.java:61)

线上版本会有crash 问题发生

**Comment by kjsolo** [comment]
类似问题
java.lang.IndexOutOfBoundsException:
Index: 2, Size: 2 at java.util.ArrayList.get(ArrayList.java:437) 
at com.tencent.msdk.dns.a.a(BackupResolv er.iava:20) 
at com.tencent.msdk.dns.DnsService.getAddrsByName(DnsService.java:14)
at com.tencent.msdk.dns.DnsService.getAddrsByName(DnsService.java:1)
