### ISSUE TITLE
MSDKDnsResolver.getAddrByName出现空指针

### ISSUE THREAD

**Issue by xuqikun** [tencentyun/httpdns-android-sdk#7]
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.tencent.msdk.dns.b.e' on a null object reference
       at com.tencent.msdk.dns.MSDKDnsResolver.getAddrByName(Unknown Source)
       at xxx.xxx.component.network.TecentHttpDNS.lookup(TecentHttpDNS.java:26)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)

**Comment by spfspfspfspfspf** [comment]
也遇到了这个问题，咋解决呢？

**Comment by weikjblue** [comment]
我们也出现这个问题  怎么解决

**Comment by xuqikun** [comment]
腾讯技术支持也没给出具体原因和方案，说是最新版本应该修复了，不过只是给的内测版还没正式发版，但是这个问题不能稳定复现，也没法验证，只能等新版发布之后更新看看了

**Comment by httpdns** [comment]
sdk旧版本上在域名解析之后的处理上存在偶现的多线程竞争读写风险，但未能在测试时复现该问题，3.0.1a之后已经尝试规避了这个问题。
