### ISSUE TITLE
版本：2.0.13a    crash

### ISSUE THREAD

**Issue by LangQiang** [tencentyun/httpdns-android-sdk#9]
版本：2.0.13a    crash  add方法 同步问题？
log：
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=10
       at java.util.ArrayList.add(ArrayList.java:442)
       at com.tencent.beacon.event.UserAction.onUserAction(SourceFile:213)
       at com.tencent.beacon.event.UserAction.onUserAction(SourceFile:195)
       at com.tencent.msdk.dns.MSDKDnsResolver.a(Unknown Source)
       at com.tencent.msdk.dns.MSDKDnsResolver.getAddrByName(Unknown Source)
       at com.redwolfama.peonylespark.start.SplashActivity$14.lookup(SourceFile:754)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(SourceFile:185)
       at okhttp3.internal.connection.RouteSelector.nextProxy(SourceFile:149)
       at okhttp3.internal.connection.RouteSelector.next(SourceFile:84)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:213)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:134)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:113)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
       at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
       at com.networkbench.agent.impl.i.b.intercept(SourceFile:61)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:200)
       at okhttp3.RealCall$AsyncCall.execute(SourceFile:147)
       at okhttp3.internal.NamedRunnable.run(SourceFile:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by LamGB** [comment]
这个是灯塔的报错。详情参看https://wiki.ssl.msdk.qq.com/src/search.html，搜ArrayIndexOutOfBoundsException。
解决方案：升级灯塔的版本。
